### ISSUE TITLE
conda-shiboken import is not consistent with pip-shiboken

### ISSUE THREAD

**Issue by looooo** [conda-forge/pyside-feedstock#31]
this is only a mini-issue:

conda: `import shiboken`
pip: `from Shiboken import shiboken`

**Comment by jschueller** [comment]
I don't know why they put it in a suddirectory, here on my linux distro it's 'import shiboken' too.
Imho the pip way is not the way upstream wants you to ship the package as the cmake variable PYTHON_SITE_PACKAGES in not set in our build.sh ; we only set the prefix so shiboken installs itself where it wants to be : not in a subdirectory of the python site dir. So afaik the pip package is shady.
