### ISSUE TITLE
pip does not find PySide installed by conda-forge

### ISSUE THREAD

**Issue by giumas** [conda-forge/pyside-feedstock#35]
After having installed `pyside` on Win 10 with Python 3.6, `pip` does not find PySide both with `pip install` and `pip list`. 

It looks a similar situation like https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/QXtqC1Y32c4

**Comment by pafonta** [comment]
Hello,

Same on macOS 10.13.2 with conda 4.4.7, Python 3.4.5, pip 9.0.1.

After `conda install -y pyside --channel conda-forge`, `pip install xyz`, where xyz has PySide as a requirement (install_requires in setup.py), tries to install PySide from PyPI.

How to make `pip` aware of the already installed PySide?

Thanks.

**Comment by jschueller** [comment]
I think it's a feature! conda packages do not have the egg files for pip, add xyz to conda forge.

**Comment by pafonta** [comment]
Thank you for your reply.

No .egg-info folder indeed (details: https://github.com/conda/conda/issues/1251).

xyz has external dependencies which are not on conda-forge. We will also move to Qt 5 soon and either use PyQt5, which is pip installable, or PySide 2, which might be [PYSIDE-558]( https://bugreports.qt.io/browse/PYSIDE-558). Besides, we would like not to have conda as a requirement at the end.

**Comment by jschueller** [comment]
You can still add xyz and its dependencies to conda-forge.
